# Generated by Django 4.1.7 on 2023-04-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('dough', models.CharField(blank=True, max_length=100, null=True)),
                ('filling', models.CharField(blank=True, max_length=100, null=True)),
                ('sauce', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('pizza_image', models.ImageField(blank=True, default='', null=True, upload_to='pizza/')),
            ],
        ),
    ]
