# Generated by Django 4.1.7 on 2023-04-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.DateField(blank=True, null=True)),
                ('floor', models.CharField(choices=[('m', 'male'), ('zh', 'woman')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='dough',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='filling',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
